[workspace]
members = [
    "crates/newvolim-io",
    "crates/newvolim-desktop",
    "crates/newvolim-portable",
    "crates/newvolim-render",
    "crates/newvolim-scene",
    "crates/newvolim-server",
    "crates/newvolim-ui",
    "crates/newvolim-decode-bench",
    "crates/newvolim-wgpu-frame",
    "crates/newvolim-residency",
]
resolver = "2"
exclude = ["palace-dev"]
